<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Privacy Policy:</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Last Updated: 21 October 2021</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">This Privacy Statement covers our policies and practices for collecting, using, and disclosing your data when you're using the service, as well as the privacy obligations as well as how the law safeguards you.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We utilize your personally identifiable information to operate and improve services. By accessing and using the services, you consent to the terms of this privacy policy in the manner described in this Privacy Policy.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>The Use of Your Personal Information</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The following are some of the extent to which a Firm may use Personal Data:</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">To offer and manage our Service, including to track and analyses how our Service is being used.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">To manage your account: This section contains information about managing your registration as a user of the Service. Access to different capabilities of the Service that are only available to you as a registered user may be granted based on the personal information you provide.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Contract performance includes the following activities: the development, compliance with and execution of a sales agreement for the products, items, or services you have purchased; and the execution of any other contract with us that you enter into through the Service.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">For the purpose of contacting You: We may contact you via electronic means such as email, telephone calls, SMS messages, or other equivalent forms of electronic communication such as push notifications from a mobile application regarding updates or insightful meaningful dialogue to the features and functionality, goods or contractual services, such as security updates, when it is necessary or sensible for their implementation.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">You have the option to opt out of receiving news, special offers, and general information from us about other items, services, and events we offer that are comparable to those you have already purchased or inquired about, unless you have indicated that you do not wish to receive such information.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">To deal with your demands, we will do the following: In order to respond to and handle youur requests to us.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">To facilitate business transfers: We may use your information to evaluate or facilitate the sale or transfer of some or all of our assets in the event that we go out of business, go into bankruptcy, liquidate, or otherwise dissolve, or in the event that we engage in any other type of business transition.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Among other things, we may use the information for data analysis, identifying usage trends, analyzing the success of our promotional efforts, and evaluating and improving our service, products, services and marketing in order to better serve you and our customers.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We may share your personal information with other parties in the following circumstances:</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">When We Share Your Information with Service Providers: We may share your personal information with service providers in order to monitor and analyze the use of our service and to contact you.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Business transfers: We may share or transfer private information in conjunction with, or through talks of, any consolidation, sell of Corporate assets, financing, or purchase of all or a component of Our business by some other company, or within the course of any other transaction with another company.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Sharing Information with Affiliates: We may share your information with our affiliates in certain circumstances. In such case, we will require such affiliates to adhere to this Privacy Policy. Affiliations include our parent firm, as well as any subsidiaries, joint venture partners, or other companies that we control or that are controlled by the same people who control or control us.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">With business partners: We may share your personal information with its business partners in order to provide you with specific products, services, or promotions that you may be interested in.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Sharing personal information or otherwise interacting in public areas with other users raises the possibility that such information may be seen by all users and may be widely spread outside of the site. It is possible that your connections on the Third-Party Social Media Service will be able to see your name, profile, images, and a description of your activity if you engage with some other users or register using the Third-Party Social Media Service. Similar to this, additional users would be able to see descriptions of your activities and communicate with you, as well as view your profile information.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">With Your Consent: We may release your personal details for other reason with your consent, if you provide us with the necessary information.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Personal Information Retention</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your Personal Data will be kept by the business around for as long as it is required for the reasons outlined in this Privacy Policy. We will keep and use Your Personal Data only as long as it is necessary to meet our legal duties (for instance, if we are obliged by law to keep your data), settle conflicts, and implement our contractual contracts and regulations.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Usage Data will be kept by the Organization for evaluation. Except where this data is used to reinforce the safety or to enhance the power of our service, or if we are lawfully compelled to preserve such information for extended durations of time, Usage Data is kept for a smaller duration of time.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Transfer of Personal Information:</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your data, especially Personal Data, is handled in the Office premises and any other locations in which the entities related to the processing are situated. It means that this information could be transferred to &mdash; and stored on &mdash; systems beyond of Your state, region, nation, or other regulatory jurisdiction, wherein data protection regulations might vary from those in your purview.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your agreement to that transfer is reflected in your acceptance of this Privacy Policy and subsequent entry of these kinds of information.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The Company might very well take all reasonable measures to protect that your information is handled safely and in conformance with these Terms, and no transmission of your Personal Information to an organization or an individual will actually occur except if regularly undertake, such as the protection of Information and other personal info, are in place.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The personal information of the client will be made public in following ways:</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Transactions in Business:</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Your Personal Data might well be transmitted if the Business is engaged in a merge, takeover, or asset sale. If your Personal Data is moved and becomes part of a separate Privacy Statement, we will notify you.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Officers of the law</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">If required by law or in response to lawful requests by governmental authorities, the Company may be required to reveal your Personal Data in certain circumstances (e.g. a court or a government agency).</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Other legal obligations:</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The Firm may release Your Personal Information if it believes in earnest that it is required to:</span></span></p>
<p lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Observe a legal requirement</span></span></p>
<p lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">The Company's rights and property must be protected and defended.</span></span></p>
<p lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Prevent or investigate any potential misbehavior involving the Service.</span></span></p>
<p lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Protect personal safety of Service users or the general public.</span></span></p>
<p lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Defend yourself from legal liability.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Your Personal Data's Safety</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We care about the safety of your Personal Information, but keep in mind that neither means of data transmission, or technique of electronic storage, is completely safe. While we make every attempt to defend your Personal Data using commercially reasonable techniques, we cannot assure its total security.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Children's Privacy</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Nobody under the age of thirteen is allowed to use our service. We do not intentionally collect personal information from children under the age of thirteen. Please notify us iu are a parent or guardian and are aware that your kid has provided us with Personal Data. If we learn that we have obtained Personal Information from anyone below the age of thirteen without parental consent, we will take measures to erase the material from the systems.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Whenever we need to depend on permission as a lawful foundation for handling your information, and your nation requires parental consent, we may need to obtain your parent's permission before collecting and using such information.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Other Websites' Links:</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Our Service could include connections to sites aren't under our control. You will be routed to the third party's website if you click on a third-party link. Each site you access should have a Privacy Policy that you should read. We have really no influence over or accountability for the contents, privacy rules, or practices of any 3rd sites or services.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><strong>Modifications to this Privacy Policy</strong></span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">We reserve the right to make changes to the Privacy Policy at any time. Any changes will be communicated to you by posting the revised Privacy Policy on this page.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">Prior to the change taking effect, we will notify you through email and/or a prominent notice on our Service, and then we shall revise the 'Last updated' mark at the head of this Privacy Policy.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">It is recommended that you examine this Privacy Policy on a regular basis for any updates. When modifications towards this Privacy Policy are published on this webpage, they become effective.</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;">If you have any queries regarding this Privacy Policy, please contact us at the following address:</span></span></p>
<p class="western" lang="en-US" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><em><strong>Email address: info@fresh2arrive.com</strong></em></span></span></p>
