 
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Website Terms of Use:</strong></span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">PLEASE READ THESE TERMS OF USE CAREFULLY. BY ACCESSING OR USING THE SERVICES PROVIDED BY FRESH2ARRIVE THRU THIS WEBSITE OR THROUGH THE FRESH2ARRIVE APP (TOGETHER REFERRED HEREINAFTER AS THE “PLATFORM”), YOU AGREE TO BE BOUND BY THE TERMS DESCRIBED HEREIN AND ALL TERMS INCORPORATED BY REFERENCE. IF YOU DO NOT AGREE TO ALL OF THESE TERMS, DO NOT USE THE SERVICES PROVIDED BY THE PLATFORM.</span></span></span></p>


<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Fresh2arrive E-Wallet (issued by ECOVEGGY PRIVATE LIMITED) Terms & Conditions</strong></span></span></span></p>
 

<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">These terms and conditions (“Terms and Conditions”) govern your use of the Prepaid fresh2arrive E-Wallet (“fresh2arrive Wallet”) created on the Platform for your usage towards ordering fresh2arrive services. This fresh2arrive Wallet is the property of ECOVEGGY PRIVATE LIMITED to whom to whom it must be surrendered, upon request. The following terms and conditions shall apply to the prepaid account of your fresh2arrive Wallet. By using the Fresh2arrive Wallet, you agree to the below mentioned Terms and Conditions. Please ensure that you have read carefully and understood these Terms and Conditions before using your Fresh2arrive Wallet and also request you to keep a copy of these Terms and Conditions for your records. You further agree that by using the Fresh2arrive Wallet, you confirm that you have read, understood and accepted the detailed Terms and Conditions of the Fresh2arrive Wallet.</span></span></span></p>


<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Eligibility</strong></span></span></span></p>

 
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">To be eligible for the Fresh2arrive Wallet membership, you should be competent to enter into a contract i.e., you should have attained the age of majority according to the Indian law. Fresh2arrive Wallet is not targeted towards, nor intended for use by anyone who has not attained the age of majority. Any person under the age of 18, may only use the Fresh2arrive Wallet under the supervision of a parent or legal guardian who agrees to be bound by these Terms and Conditions.</span></span></span></p>


<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">About Your Account</span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">Fresh2arrive Wallet is issued to you by ECOVEGGY PRIVATE LIMITED. It allows you to load a rupee value onto your Fresh2arrive Wallet for use only on on Fresh2arrive Platform. The value associated with the Fresh2arrive Wallet is not insured or guaranteed by any person or entity.
The rupee value that you load onto your Fresh2arrive Wallet is a prepayment only for purchasing the goods and availing the services on Fresh2arrive Platform in India unless otherwise specified.
Fresh2arrive Wallet can be loaded on Fresh2arrive Platform using either cash / credit card / debit card / upi / Internet Banking / any other RBI approved e-wallets managed and governed by other private or government entities. One Fresh2arrive Wallet cannot be reloaded by using any other registered/unregistered Fresh2arrive Wallet.
ECOVEGGY PRIVATE LIMITED reserves the right not to accept any Fresh2arrive Wallet or otherwise limit use of a Fresh2arrive Wallet if we reasonably believe that the use is unauthorized, fraudulent or otherwise unlawful. Further, misuse of the Fresh2arrive Wallet or its benefits in any manner may result in disablement of the Fresh2arrive Wallet and/or withdrawal of benefits at the sole discretion of ECOVEGGY PRIVATE LIMITED. Please maintain the Fresh2arrive Wallet safely and securely.</span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Loading Value in your Fresh2arrive Wallet:</strong></span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">Fresh2arrive Wallet is automatically created and enabled as soon as you register for Fresh2arrive Platform’s services while accepting these Terms and Conditions. The wallet gets activated by loading money in it either through credit card / debit card / upi / Internet Banking / any other RBI approved e-wallets managed and governed by other private or government entities by visiting the Fresh2arrive website or Fresh2arrive mobile app. Fresh2arrive Wallet can be used as a mode of payment, whenever the Fresh2arrive Wallet-holder purchases goods or services from Fresh2arrive website or Fresh2arrive mobile app. We provide Welcome Bonus amount that be initially loaded onto your Fresh2arrive Wallet is INR 51 (Rupees Fifty One only). The balance on the Fresh2arrive Wallet does not have a validity or expiry period.
ECOVEGGY PRIVATE LIMITED may change the maximum and minimum amounts at any time by notifying you at the point of recharge, or on the Fresh2arrive website (www.fresh2arrive.com), and such change shall not constitute an amendment to these Terms and Conditions. No credit card, credit line, overdraft protection or deposit account is associated with a Fresh2arrive Wallet. The balance loaded onto your Fresh2arrive Wallet is non-refundable and may not be exchanged for cash or credit balance unless required by law in India. No interest, dividends or any other earnings on funds deposited to a Fresh2arrive Wallet will accrue or be paid or credited to you by ECOVEGGY PRIVATE LIMITED.
All amounts loaded onto your Fresh2arrive Wallet are held and denominated in Indian Rupees.</span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Fees and Expiration of Wallet Balances:</strong></span></span></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">ECOVEGGY PRIVATE LIMITED reserves its right, in its sole discretion and without any prior notice, to impose and/or revise charges/commissions in relation to your use of the Fresh2arrive Wallet. The current charges for your Wallet are provided hereunder, the same are subject to change;</span></span></span></p>


<p>All charges mentioned above are exclusive of applicable taxes including GST</p>







<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US">Receipts and Statements
Fresh2arrive Wallet holders are not sent statements of itemized transactions on their registered email id from a Fresh2arrive Wallet account. You can check the balance of your Fresh2arrive Wallet or review recent transactions on your Fresh2arrive Wallet by logging into your Fresh2arrive account on www.fresh2arrive.com. or on the Fresh2arrive mobile app.
You will need to use your Fresh2arrive Wallet to make purchases for the goods and availing the services on Fresh2arrive Platform. When you use your Fresh2arrive Wallet, you will receive the details of your order and payment in the Account History section of your Fresh2arrive account. The Shopping Credits section of your Fresh2arrive Account will provide the remaining balance of your Fresh2arrive Wallet. You should check your order and payments details to ensure that your account balance is correct 
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Billing Errors, Corrections </strong></span></p>
ECOVEGGY PRIVATE LIMITED reserves the right to correct the balance of your Fresh2arrive Wallet if there is reason to believe that a clerical, billing or accounting error has occurred. If you have questions regarding your transaction history or any correction, or if you dispute any transaction or correction that has been assessed against your Fresh2arrive Wallet, please email your concern at <a href="info@fresh2arrive.com">info@fresh2arrive.com</a>. ECOVEGGY PRIVATE LIMITED will conduct an investigation and communicate the results and correct any error that after conducting a thorough investigation in a reasonable time-frame. If no error is found, a suitable explanation shall be communicated to you. ECOVEGGY PRIVATE LIMITED shall have no liability for any billing error unless you provide a notice within 30 days of the date of the transaction in question. You are requested to monitor your transactions and account balances accurately.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Registration, Liability for Unauthorized Transactions</strong></span></p>
You are responsible for all transactions associated with your Fresh2arrive Wallet, including transactions claimed to be unauthorised. The Fresh2arrive Wallet does not have a separate authentication password or PIN and can be used to make transactions once you have logged-in to the platform using Mobile Number-Password combination or Mobile number-OTP authentication. The mobile application remains in a state of permanent log-in and anyone with access to your mobile phone can have access to your application and thereafter use your Fresh2arrive Wallet. You agree to take full responsibility of any unintended or unauthorised access to your Fresh2arrive Wallet.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Blocking of Fresh2arrive Wallet:</strong></span></p>
ECOVEGGY PRIVATE LIMITED reserves the right to block your Fresh2arrive Wallet and/or discontinue, if ECOVEGGY PRIVATE LIMITED determines or observes in its sole discretion that there has been any fraudulent or unauthorized activities through your Fresh2arrive Wallet.
Privacy Statement
You hereby authorise ECOVEGGY PRIVATE LIMITED to disclose your information to Government authorities or to competent authorities or to credit bureaus or to other third persons, to comply with the obligation under the law. You also authorise ECOVEGGY PRIVATE LIMITED to use your information for offering product and services to you, including from its associates/partners unless specified otherwise.
For information concerning how we collect, use and disclose information concerning the Fresh2arrive Wallet and how to select privacy preferences regarding certain promotional communications, you should refer to our privacy statement mentioned on our website - https://www.fresh2arrive.com/privacy-policy.html
    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Changes to these Terms and Conditions </strong></span></p>
ECOVEGGY PRIVATE LIMITED reserves the right to add, alter, amend and revise terms and conditions as well as the rules and regulations governing the Fresh2arrive Wallet without prior notice, and without assigning any reasons thereof. In the event of such changes, the latest terms & conditions will be updated and viewed on our website www.fresh2arrive.com
Cancellation of these Terms and Conditions
We may suspend or terminate these terms and conditions and revoke or limit any or all of the rights and privileges granted to you at any time without notice or liability. Termination may also result from your fraudulent or unauthorized use of the Fresh2arrive Wallet.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Governing Law</strong></span></p>
All disputes, in connection with Fresh2arrive Wallet or its program shall be governed and construed in accordance with Indian Laws and are subject to the exclusive jurisdiction of Competent Courts at Gautam Buddha Nagar, Uttar Pradesh only.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Disclaimers and Limits of Liability</strong></span></p>
ECOVEGGY PRIVATE LIMITED and its affiliates make no representations, warranties or conditions of any kind, express or implied, with respect to the Fresh2arrive Wallet, including, but not limited to, any implied warranty of merchantability, fitness for a particular purpose, title, or non-infringement, or any warranty arising by usage of trade, course of dealing or course of performance. ECOVEGGY PRIVATE LIMITED does not represent or warrant that your Fresh2arrive Wallets will always be accessible or accepted.
In the event that ECOVEGGY PRIVATE LIMITED or its affiliates are found liable to you, you shall only be entitled to recover actual and direct damages and such damages shall not exceed the last balance held on your Fresh2arrive Wallet. ECOVEGGY PRIVATE LIMITED and its affiliates shall have no liability for any incidental, indirect or consequential damages (including without limitation loss of profit, revenue or use) arising out of or in any way connected with this Agreement, whether in contract, warranty, tort (including negligence, whether active, passive or imputed), product liability, strict liability or other theory, even if ECOVEGGY PRIVATE LIMITED or its authorized representatives have been advised of the possibility of such damages. In no event shall ECOVEGGY PRIVATE LIMITED or its affiliates have any liability for unauthorized access to, or alteration, theft or destruction of a Fresh2arrive Wallet through accident, misuse or fraudulent means or devices by you or any third party, or as a result of any delay or mistake resulting from any circumstances beyond our control. ECOVEGGY PRIVATE LIMITED is not liable for non-fulfilment of any terms in full or in part due to any reason beyond its control.
The laws of certain states or other jurisdiction do not allow limitations on implied warranties, or the exclusion or limitation of certain damages. If these laws apply, some or all of the above disclaimers, exclusions or limitations may not apply to you, and you may have rights in addition to those contained in this Terms and Conditions. In such jurisdiction, our liability is limited to the greatest extent permitted by law.
The decision of the management of ECOVEGGY PRIVATE LIMITED is final and shall be binding at all times.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Assignment</strong></span></p>
We may assign all or part of these Terms and Conditions without such assignment being considered a change to these Terms and Conditions and without notice to you and shall be released from all liabilities The assignee shall have the same rights and obligations as the assignor and shall agree in writing to be bound by the Terms and Conditions.
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Entire Terms and Conditions, Construction</strong></span></p>
These Terms and Conditions is the complete and exclusive between you and ECOVEGGY PRIVATE LIMITED, and supersedes and merges all prior proposals and all or any other prior arrangement/agreements. In the event that any provision of these Terms and Conditions shall be determined to be illegal or unenforceable, that provision will be eliminated to the minimum extent necessary so that these Terms and Conditions shall otherwise remain in full force, effect and shall be enforceable. Headings herein are for convenience of reference only and shall in no way affect interpretation of these Terms and Conditions.
<a href="#">Copyright & Trademark</a>
ECOVEGGY PRIVATE LIMITED and its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on Fresh2arrive Platform. Access to this Platform does not confer and shall not be considered as conferring upon anyone any license under any of ECOVEGGY PRIVATE LIMITED or any third party's intellectual property rights. All rights, including copyright, in this Platform are owned by or licensed to ECOVEGGY PRIVATE LIMITED. Any use of this Platform or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of ECOVEGGY PRIVATE LIMITED. You may not modify, distribute or re-post anything on this Platform for any purpose.
The names and logos and all related product and service names, design marks and slogans are the trademarks or service marks of ECOVEGGY PRIVATE LIMITED, its affiliates, its partners or its suppliers. All other marks are the property of their respective companies. No trademark or service mark, license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.
References on this Platform to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply ECOVEGGY PRIVATE LIMITED endorsement, sponsorship or recommendation of the third party, information, product or service.
ECOVEGGY PRIVATE LIMITED is not responsible for the content of any third-party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third-party websites, you do so entirely at your own risk.
All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Website (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Website or any related software. All software used on this Website is the property of ECOVEGGY PRIVATE LIMITED  or its licensees and suppliers and protected by Indian and international copyright laws. The Contents and software on this Website may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Website is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by ECOVEGGY PRIVATE LIMITED, one of its affiliates or by third parties who have licensed their materials to ECOVEGGY PRIVATE LIMITED and are protected by Indian and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this Website is the exclusive property of ECOVEGGY PRIVATE LIMITED and is also protected by Indian and international copyright laws.
All rights not expressly granted are reserved.
In case of any grievances, you can contact:
    <p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>--Address Details:</strong></span></p>
ECOVEGGY PRIVATE LIMITED 
CIN: U74999UP2021PTC150965
9121 9TH Floor Redwood Tower 
Mahagun Mywoods Sector 16C 
Greater Noida West Extension
Gautam Buddha Nagar-201306
Uttar Pradesh

Tel.: +91 9990194488
Email id: info@fresh2arrive.com

<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Terms and Conditions </strong></span></p>
<p align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span lang="en-US"><strong>Personal Information </strong></span></p>
ECOVEGGY PRIVATE LIMITED is the licensed owner of the brand Fresh2arrive and the website www.fresh2arrive.com (” The Site”). ECOVEGGY PRIVATE LIMITED respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by ECOVEGGY PRIVATE LIMITED on the Site. As a visitor to the Site/ Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by ECOVEGGY PRIVATE LIMITED in the manner provided in this Privacy Policy.
<br/><br/><a href="#">Services overview</a><br/><br/>
As part of the registration process on the Site, ECOVEGGY PRIVATE LIMITED may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information.
<br/><br/><a href="#">Eligibility</a><br/><br/>
Services of the Site would be available to only selected geographies in India. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. If you are a minor i.e., under the age of 18 years but at least 13 years of age you may use the Site only under the supervision of a parent or legal guardian who agrees to be bound by these Terms of Use. If your age is below 18 years your parents or legal guardians can transact on behalf of you if they are registered users. You are prohibited from purchasing any material which is for adult consumption and the sale of which to minors is prohibited.
<br/><br/><a href="#">License & Site access</a><br/><br/>
ECOVEGGY PRIVATE LIMITED grants you a limited sub-license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except with express written consent of ECOVEGGY PRIVATE LIMITED. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of ECOVEGGY PRIVATE LIMITED. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Site or of ECOVEGGY PRIVATE LIMITED and its affiliates without express written consent. You may not use any meta tags or any other "hidden text" utilizing the Site’s or ECOVEGGY PRIVATE LIMITED’s name or trademarks without the express written consent of ECOVEGGY PRIVATE LIMITED. Any unauthorized use terminates the permission or license granted by ECOVEGGY PRIVATE LIMITED.
<br/><br/><a href="#">Account & Registration Obligations</a><br/><br/>
All customer have to register and login for placing orders on the Site. You have to keep your account and registration details current and correct for communications related to your purchases from the site. By agreeing to the terms and conditions, the shopper agrees to receive promotional communication and newsletters upon registration. The customer can opt out either by unsubscribing in "My Account" or by contacting the customer service. However, Account created on the website www.fresh2arrive.com would be for life time of the customers.
<br/><br/><a href="#">Pricing</a><br/><br/>
All the products listed on the Site will be sold at MRP unless otherwise specified. The prices mentioned at the time of ordering will be the prices charged on the date of the delivery. Although prices of most of the products do not fluctuate on a daily basis but some of the commodities and fresh food prices do change on a daily basis. In case the prices are higher or lower on the date of delivery no additional charges will be collected or refunded as the case may be at the time of the delivery of the order.
Cancellation by Site / Customer
You as a customer can cancel your order anytime up to the cut-off time of the slot for which you have placed an order by calling our customer service. In such a case we will refund any payments already made by you for the order. If we suspect any fraudulent transaction by any customer or any transaction which defies the terms & conditions of using the website, we at our sole discretion could cancel such orders. We will maintain a negative list of all fraudulent transactions and customers and would deny access to them or cancel any orders placed by them.
<br/><br/><a href="#">Return & Refunds</a><br/><br/>
Our Return and Refund policy entitles all our members to return the product at the time of delivery if due to some reason they are not satisfied with the quality or freshness of the product. We will take the returned product back with us and issue a credit note for the value of the return products which will be credited to your account on the Site. This can be used to pay your subsequent shopping bills.
You Agree and Confirm
   <br/> 1. That in the event that a non-delivery occurs on account of a mistake by you (i.e., wrong name or address or any other wrong information) any extra cost incurred by ECOVEGGY PRIVATE LIMITED for redelivery shall be claimed from you.<br/>
  <br/>  2. That you will use the services provided by the Site, its affiliates, consultants and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using and transacting on the Site.<br/>
    <br/>3. You will provide authentic and true information in all instances where such information is requested of you. ECOVEGGY PRIVATE LIMITED reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), it has the right in its sole discretion to reject the registration and debar you from using the Services and / or other affiliated websites without prior intimation whatsoever.<br/>
  <br/>  4. That you are accessing the services available on this Site and transacting at your sole risk and are using your best and prudent judgment before entering into any transaction through this Site.<br/>
   <br/> 5. That the address at which delivery of the product ordered by you is to be made will be correct and proper in all respects.<br/>
  <br/>  6. That before placing an order you will check the product description carefully. By placing an order for a product, you agree to be bound by the conditions of sale included in the item's description.<br/><br/>
    <a href="#">You may not use the Site for any of the following purposes:</a><br/>
   <br/> 1. Disseminating any unlawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material.<br/>
    <br/>2. Transmitting material that encourages conduct that constitutes a criminal offence or results in civil liability or otherwise breaches any relevant laws, regulations or code of practice.<br/>
   <br/> 3. Gaining unauthorized access to other computer systems.<br/>
  <br/>  4. Interfering with any other person's use or enjoyment of the Site.<br/>
    <br/>5. Breaching any applicable laws;<br/>
    <br/>6. Interfering or disrupting networks or web sites connected to the Site.<br/>
   <br/> 7. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner.
   <br/><br/> <a href="#">Colours</a><br/><br/>
We have made every effort to display the colours of our products that appear on the Website as accurately as possible. However, as the actual colours you see will depend on your monitor, we cannot guarantee that your monitor's display of any colour will be accurate.
 <br/><br/> <a href="#">Modification of Terms & Conditions of Service</a><br/><br/>
ECOVEGGY PRIVATE LIMITED may at any time modify the Terms & Conditions of Use of the Website without any prior notification to you. You can access the latest version of these Terms & Conditions at any given time on the Site. You should regularly review the Terms & Conditions on the Site. In the event the modified Terms & Conditions is not acceptable to you, you should discontinue using the Service. However, if you continue to use the Service you shall be deemed to have agreed to accept and abide by the modified Terms & Conditions of Use of this Site.
 <br/><br/> <a href="#">Governing Law and Jurisdiction</a><br/><br/>
This User Agreement shall be construed in accordance with the applicable laws of India. The Courts at GAUTAM BUDDHA NAGAR UP shall have exclusive jurisdiction in any proceedings arising out of this agreement. Any dispute or difference either in interpretation or otherwise, of any terms of this User Agreement between the parties hereto, the same shall be referred to an independent arbitrator who will be appointed by ECOVEGGY PRIVATE LIMITED and his decision shall be final and binding on the parties hereto. The above arbitration shall be in accordance with the Arbitration and Conciliation Act, 1996 as amended from time to time. The arbitration shall be held in GAUTAM BUDDHA NAGAR UP. The High Court of judicature at UTTAR PRADESH alone shall have the jurisdiction and the Laws of India shall apply.
 <br/><br/> <a href="#">Reviews, Feedback, Submissions</a><br/><br/>
All reviews, comments, feedback, postcards, suggestions, ideas, and other submissions disclosed, submitted or offered to the Site on or by this Site or otherwise disclosed, submitted or offered in connection with your use of this Site (collectively, the "Comments") shall be and remain the property of ECOVEGGY PRIVATE LIMITED. Such disclosure, submission or offer of any Comments shall constitute an assignment to ECOVEGGY PRIVATE LIMITED of all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments. Thus, ECOVEGGY PRIVATE LIMITED owns exclusively all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments. ECOVEGGY PRIVATE LIMITED will be entitled to use, reproduce, disclose, modify, adapt, create derivative works from, publish, display and distribute any Comments you submit for any purpose whatsoever, without restriction and without compensating you in any way. ECOVEGGY PRIVATE LIMITED is and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay you any compensation for any Comments; or (3) to respond to any Comments. You agree that any Comments submitted by you to the Site will not violate this policy or any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s), and will not cause injury to any person or entity. You further agree that no Comments submitted by you to the Website will be or contain libellous or otherwise unlawful, threatening, abusive or obscene material, or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of "spam".
ECOVEGGY PRIVATE LIMITED does not regularly review posted Comments, but does reserve the right (but not the obligation) to monitor and edit or remove any Comments submitted to the Site. You grant ECOVEGGY PRIVATE LIMITED the right to use the name that you submit in connection with any Comments. You agree not to use a false email address, impersonate any person or entity, or otherwise mislead as to the origin of any Comments you submit. You are and shall remain solely responsible for the content of any Comments you make and you agree to indemnify ECOVEGGY PRIVATE LIMITED and its affiliates for all claims resulting from any Comments you submit. ECOVEGGY PRIVATE LIMITED and its affiliates take no responsibility and assume no liability for any Comments submitted by you or any third party.
<br/><br/> <a href="#">Copyright & Trademark</a><br/><br/>
ECOVEGGY PRIVATE LIMITED and  its suppliers and licensors expressly reserve all intellectual property rights in all text, programs, products, processes, technology, content and other materials, which appear on this Site. Access to this Website does not confer and shall not be considered as conferring upon anyone any license under any of ECOVEGGY PRIVATE LIMITED or any third party's intellectual property rights. All rights, including copyright, in this website are owned by or licensed to ECOVEGGY PRIVATE LIMITED. Any use of this website or its contents, including copying or storing it or them in whole or part, other than for your own personal, non-commercial use is prohibited without the permission of ECOVEGGY PRIVATE LIMITED. You may not modify, distribute or re-post anything on this website for any purpose.
The names and logos and all related product and service names, design marks and slogans are the trademarks or service marks ECOVEGGY PRIVATE LIMITED, its affiliates, its partners or its suppliers. All other marks are the property of their respective companies. No trademark or service mark, license is granted in connection with the materials contained on this Site. Access to this Site does not authorize anyone to use any name, logo or mark in any manner.
References on this Site to any names, marks, products or services of third parties or hypertext links to third party sites or information are provided solely as a convenience to you and do not in any way constitute or imply ECOVEGGY PRIVATE LIMITED endorsement, sponsorship or recommendation of the third party, information, product or service.
ECOVEGGY PRIVATE LIMITED is not responsible for the content of any third-party sites and does not make any representations regarding the content or accuracy of material on such sites. If you decide to link to any such third-party websites, you do so entirely at your own risk.
All materials, including images, text, illustrations, designs, icons, photographs, programs, music clips or downloads, video clips and written and other materials that are part of this Website (collectively, the "Contents") are intended solely for personal, non-commercial use. You may download or copy the Contents and other downloadable materials displayed on the Website for your personal use only. No right, title or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce (except as noted above), publish, transmit, distribute, display, modify, create derivative works from, sell or participate in any sale of or exploit in any way, in whole or in part, any of the Contents, the Website or any related software. All software used on this Website is the property of ECOVEGGY PRIVATE LIMITED or its licensees and suppliers and protected by Indian and international copyright laws. The Contents and software on this Website may be used only as a shopping resource. Any other use, including the reproduction, modification, distribution, transmission, republication, display, or performance, of the Contents on this Website is strictly prohibited. Unless otherwise noted, all Contents are copyrights, trademarks, trade dress and/or other intellectual property owned, controlled or licensed by ECOVEGGY PRIVATE LIMITED, one of its affiliates or by third parties who have licensed their materials to ECOVEGGY PRIVATE LIMITED and are protected by Indian and international copyright laws. The compilation (meaning the collection, arrangement, and assembly) of all Contents on this Website is the exclusive property of ECOVEGGY PRIVATE LIMITED and is also protected by Indian and international copyright laws.
<br/><br/> <a href="#">Objectionable Material</a><br/><br/>
You understand that by using this Site or any services provided on the Site, you may encounter Content that may be deemed by some to be offensive, indecent, or objectionable, which Content may or may not be identified as such. You agree to use the Site and any service at your sole risk and that to the fullest extent permitted under applicable law. ECOVEGGY PRIVATE LIMITED and its affiliates shall have no liability to you for Content that may be deemed offensive, indecent, or objectionable to you.
<br/><br/> <a href="#">Indemnity</a><br/><br/>
You agree to defend, indemnify and hold harmless ECOVEGGY PRIVATE LIMITED, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to ECOVEGGY PRIVATE LIMITED or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfilment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.
<br/><br/> <a href="#">Termination</a><br/><br/>
This User Agreement is effective unless and until terminated by either you or ECOVEGGY PRIVATE LIMITED. You may terminate this User Agreement at any time, provided that you discontinue any further use of this Site. ECOVEGGY PRIVATE LIMITED may terminate this User Agreement at any time and may do so immediately without notice, and accordingly deny you access to the Site, such termination will be without any liability to ECOVEGGY PRIVATE LIMITED. However, Account created on the website www.fresh2arrive.com would be for life time of the customers. Upon any termination of the User Agreement by either you or ECOVEGGY PRIVATE LIMITED, you must promptly destroy all materials downloaded or otherwise obtained from this Site, as well as all copies of such materials, whether made under the User Agreement or otherwise. ECOVEGGY PRIVATE LIMITED's right to any Comments shall survive any termination of this User Agreement. Any such termination of the User Agreement shall not cancel your obligation to pay for the product already ordered from the Website or affect any liability that may have arisen under the User Agreement.
<br/><br/> <a href="#">Privacy Policy</a><br/><br/>
<b>Personal Information</b><br/><br/>
ECOVEGGY PRIVATE LIMITED is the licensed owner of the brand fresh2arrive and the website www.fresh2arrive.com (” The Site”). ECOVEGGY PRIVATE LIMITED respects your privacy. This Privacy Policy provides succinctly the manner your data is collected and used by ECOVEGGY PRIVATE LIMITED on the Site. As a visitor to the Site/ Customer you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by ECOVEGGY PRIVATE LIMITED in the manner provided in this Privacy Policy.
<br/><br/> <a href="#">What information is, or may be, collected from you?</a><br/><br/>
As part of the registration process on the Site, ECOVEGGY PRIVATE LIMITED may collect the following personally identifiable information about you: Name including first and last name, alternate email address, mobile, phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information.
<br/><br/> <a href="#">How do we collect the Information?</a><br/><br/>
ECOVEGGY PRIVATE LIMITED will collect personally identifiable information about you only as part of a voluntary registration process, on-line survey or any combination thereof. The Site may contain links to other Web sites. ECOVEGGY PRIVATE LIMITED is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the Double Click cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site.
<br/><br/> <a href="#">How is information used?</a><br/><br/>
ECOVEGGY PRIVATE LIMITED will use your personal information to provide personalized features to you on the Site and to provide promotional offers to you through the Site and other channels. ECOVEGGY PRIVATE LIMITED will also provide this information to its business associates and partners to get in touch with you when necessary to provide the services requested by you. ECOVEGGY PRIVATE LIMITED will use this information to preserve transaction history as governed by existing law or policy. ECOVEGGY PRIVATE LIMITED may also use contact information internally to direct its efforts for product improvement, to contact you as a survey respondent, to notify you if you win any contest; and to send you promotional materials from its contest sponsors or advertisers. ECOVEGGY PRIVATE LIMITED will also use this information to serve various promotional and advertising materials to you via display advertisements through the Google Ad network on third party websites. You can opt out of Google Analytics for Display Advertising and customize Google Display network ads using the Ads Preferences Manager. Information about Customers on an aggregate (excluding any information that may identify you specifically) covering Customer transaction data and Customer demographic and location data may be provided to partners of ECOVEGGY PRIVATE LIMITED for the purpose of creating additional features on the website, creating appropriate merchandising or creating new products and services and conducting marketing research and statistical analysis of customer behaviour and transactions.
<br/><br/> <a href="#">With whom your information will be shared</a><br/><br/>
ECOVEGGY PRIVATE LIMITED will not use your financial information for any purpose other than to complete a transaction with you. ECOVEGGY PRIVATE LIMITED does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services you've requested and such information is necessary to provide these products or services the information may be shared with ECOVEGGY PRIVATE LIMITED’s business associates and partners. ECOVEGGY PRIVATE LIMITED may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition, ECOVEGGY PRIVATE LIMITED may use this information for promotional offers, to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, potential threat to the safety or security of any person, violations of the Site’s terms of use or to defend against legal claims; special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure.
<br/><br/> <a href="#">What choice are available to you regarding collection, use and distribution of your information?</a><br/><br/>
To protect against the loss, misuse and alteration of the information under its control, ECOVEGGY PRIVATE LIMITED has in place appropriate physical, electronic and managerial procedures. For example, ECOVEGGY PRIVATE LIMITED servers are accessible only to authorized personnel and your information is shared with employees and authorised personnel on a need-to-know basis to complete the transaction and to provide the services requested by you. Although ECOVEGGY PRIVATE LIMITED will endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this site, you agree that ECOVEGGY PRIVATE LIMITED will have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties.
<br/><br/> <a href="#">How can you correct inaccuracies in the information?</a><br/><br/>
To correct or update any information you have provided, the Site allows you to do it online. In the event of loss of access details, you can send an e-mail to: <a href="info@fresh2arrive.com">info@fresh2arrive.com</a>
<br/><br/> <a href="#">Policy updates</a><br/><br/>
ECOVEGGY PRIVATE LIMITED reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the Site.
<br/><br/> <a href="#">Contact Information</a><br/><br/>
ECOVEGGY PRIVATE LIMITED 
CIN: U74999UP2021PTC150965
9121 9TH Floor Redwood Tower 
Mahagun Mywoods Sector 16C 
Greater Noida West Extension
Gautam Buddha Nagar-201306
Uttar Pradesh
<br/><br/>
Tel.: +91 9990194488
Email id: <a href="info@fresh2arrive.com">info@fresh2arrive.com</a>
<br/><br/>
  </span></span></span></p>
 
